default: instance_generator.cpp instance_generator2.cpp
	g++ instance_generator.cpp -o instance_generator -Wall -std=c++11
	g++ instance_generator2.cpp -o instance_generator2 -Wall -std=c++11

test: default
	./instance_generator
